#!/bin/sh

MSG_FILE="$1"

if command -v node >/dev/null 2>&1; then
	node scripts/generate-commit-msg.cjs "$MSG_FILE"
	exit 0
fi

if command -v node.exe >/dev/null 2>&1; then
	node.exe scripts/generate-commit-msg.cjs "$MSG_FILE"
	exit 0
fi
